### ISSUE TITLE
application start up failed

### ISSUE THREAD

**Issue by kedbirhan** [sothawo/blog-sde-multiple-entities#1]
Hi Sir i tried to run the app unfortunately it fails on start when calling  indexOperations.putTemplate(putTemplateRequest);
i have found similar issue on elasticsearch repo on github in [this](https://github.com/elastic/elasticsearch/issues/56896) link. I am not sure it its elasticsearch compatibility issues. I am running 7.10.0.

`org.springframework.data.elasticsearch.UncategorizedElasticsearchException: Unable to parse response body; nested exception is ElasticsearchStatusException[Unable to parse response body]; nested: ResponseException[method [PUT], host [http://localhost:9200], URI [/_template/blog-sde-log-template?master_timeout=30s], status line [HTTP/1.1 404 ]
{"timestamp":"2022-05-30T00:19:15.833+00:00","status":404,"error":"Not Found","message":"","path":"/_template/blog-sde-log-template"}];
	at org.springframework.data.elasticsearch.core.ElasticsearchExceptionTranslator.translateExceptionIfPossible(ElasticsearchExceptionTranslator.java:66) ~[spring-data-elasticsearch-4.1.8.jar:4.1.8]
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:362) ~[spring-data-elasticsearch-4.1.8.jar:4.1.8]
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:345) ~[spring-data-elasticsearch-4.1.8.jar:4.1.8]
	at org.springframework.data.elasticsearch.core.DefaultIndexOperations.putTemplate(DefaultIndexOperations.java:217) ~[spring-data-elasticsearch-4.1.8.jar:4.1.8]
	at com.sothawo.blogsdemultipleentities.BlogSdeMultipleEntitiesApplication.initIndexTemplates(BlogSdeMultipleEntitiesApplication.java:29) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79) ~[spring-boot-2.4.5.jar:2.4.5]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:354) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) ~[spring-boot-2.4.5.jar:2.4.5]
	at com.sothawo.blogsdemultipleentities.BlogSdeMultipleEntitiesApplication.main(BlogSdeMultipleEntitiesApplication.java:20) ~[classes/:na]
Caused by: org.elasticsearch.ElasticsearchStatusException: Unable to parse response body
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1872) ~[elasticsearch-rest-high-level-client-7.9.3.jar:7.9.3]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1626) ~[elasticsearch-rest-high-level-client-7.9.3.jar:7.9.3]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583) ~[elasticsearch-rest-high-level-client-7.9.3.jar:7.9.3]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553) ~[elasticsearch-rest-high-level-client-7.9.3.jar:7.9.3]
	at org.elasticsearch.client.IndicesClient.putTemplate(IndicesClient.java:1419) ~[elasticsearch-rest-high-level-client-7.9.3.jar:7.9.3]
	at org.springframework.data.elasticsearch.core.DefaultIndexOperations.lambda$putTemplate$12(DefaultIndexOperations.java:218) ~[spring-data-elasticsearch-4.1.8.jar:4.1.8]
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:343) ~[spring-data-elasticsearch-4.1.8.jar:4.1.8]
	... 24 common frames omitted
	Suppressed: org.elasticsearch.common.ParsingException: Failed to parse object: expecting field with name [error] but found [timestamp]
		at org.elasticsearch.common.xcontent.XContentParserUtils.ensureFieldName(XContentParserUtils.java:50) ~[elasticsearch-7.9.3.jar:7.9.3]
		at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:592) ~[elasticsearch-7.9.3.jar:7.9.3]
		at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:179) ~[elasticsearch-7.9.3.jar:7.9.3]
		at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1892) ~[elasticsearch-rest-high-level-client-7.9.3.jar:7.9.3]
		at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1869) ~[elasticsearch-rest-high-level-client-7.9.3.jar:7.9.3]
		... 30 common frames omitted
Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://localhost:9200], URI [/_template/blog-sde-log-template?master_timeout=30s], status line [HTTP/1.1 404 ]
{"timestamp":"2022-05-30T00:19:15.833+00:00","status":404,"error":"Not Found","message":"","path":"/_template/blog-sde-log-template"}
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:302) ~[elasticsearch-rest-client-7.9.3.jar:7.9.3]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272) ~[elasticsearch-rest-client-7.9.3.jar:7.9.3]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) ~[elasticsearch-rest-client-7.9.3.jar:7.9.3]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613) ~[elasticsearch-rest-high-level-client-7.9.3.jar:7.9.3]
	... 29 common frames omitted

2022-05-29 20:19:15.887  INFO 29146 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'

Process finished with exit code 1
`

**Comment by kedbirhan** [comment]
i removed the proxy argument  in the elasticsearch client creation now its working.

        ClientConfiguration clientConfiguration = ClientConfiguration.builder() //
            .connectedTo("localhost:9200") //
//            .withProxy("localhost:8080")
            .build();
not sure why it worked though

**Comment by sothawo** [comment]
thanks for the hint, I removed that proxy setting from the code.
